import Providers from "@/components/Providers";
import CenterPanel from "@/components/screen/CenterPanel";
import LeftPanel from "@/components/screen/LeftPanel";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex max-w-screen-monitor bg-black font-sans text-white`}
      >
        <Providers>
          <LeftPanel />
          <CenterPanel>{children}</CenterPanel>
          <div className="hidden flex-1 overflow-hidden p-2 monitor:block" />
        </Providers>
      </body>
    </html>
  );
}
